file= open('hello.txt','w')
file.write("hello ali\nwelcom to python")
file=open('hello.txt','r')
text=file.read()
print(text)
file=open('hello.txt','a')
file.write('\nToday is Day 9\n')

name=input('enter your name:\n')
file=open('hello.txt','a')
file.write(name)
file=open('hello.txt','r')
text=file.read()
print(text)